---
title: "Tests of `flexdashboard` functionalities"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: 
      version: 4
      bootswatch: litera
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo = F}

# knitr::opts_chunk$set(echo = F)
# Sys.setlocale("LC_TIME", "English") # language = English, does not work right now

# fundamentals
library(flexdashboard)
library(etn)
library(knitr)
library(shiny)

# data wrangling
library(readr)
library(tidyverse)
library(lubridate)
library(dplyr)
library(lubridate)
library(utils)
library(tidyverse)

# maps
library(leaflet)
library(leafem)

# plotting and tables
library(DT) # for interactive tables
library(ggplot2)
library(kableExtra)
library(plotly)
library(scico) #colour palettes
library(gridExtra)
library(ggridges)

# database connection
con <- etn::connect_to_etn(Sys.getenv("userid"), Sys.getenv("pwd"))

```


```{r database query, include=FALSE, echo=FALSE}

species_name <- "Squalus acanthias"

# get all animals with the species name 'squalus acanthias'
# GIVES EMPTY DF
# animals <- etn::get_animals(con, scientific_name = species_name)

# ANIMALS
path_animals <- paste0(getwd(), "/data/Squalus_acanthias_animals.csv")
animals <- utils::read.table(file = path_animals, 
                            header = T,
                            sep = ",")
relevant_columns_animals <- c("tag", "catchedDateTime", "idPk", "utcReleaseDateTime", "scientificName", "releaseLatitude", "releaseLongitude", "sex")

# TAGGING LOCATIONS
tagging_locations <- animals %>% 
    dplyr::mutate(releaseLatLon = paste0(releaseLatitude, ", ", releaseLongitude)) %>% 
    group_by(releaseLatLon) %>%
    summarise(releaseLatitude = mean(releaseLatitude),
              releaseLongitude = mean(releaseLongitude)) %>%
  dplyr::select(-releaseLatLon) %>%
  dplyr::arrange(releaseLatitude) %>%
  dplyr::mutate(tagging_location = c("1_start_LochEtive", "2_mid_LochEtive", "3_end_LochEtive")) #Name tagging locations

# add tagging location names to animals
animals <- animals %>%
  dplyr::left_join(tagging_locations %>% dplyr::select(releaseLatitude, tagging_location), by = join_by(releaseLatitude))

tagging_locations <- tagging_locations %>%
  dplyr::left_join(animals %>% group_by(tagging_location) %>% summarise(ind_tagged = n()),
                   by = join_by(tagging_location))


# DETECTIONS
detections <- etn::get_acoustic_detections(scientific_name = species_name)  %>%
  dplyr::left_join(animals %>% dplyr::select(idPk, sex),
                   by = join_by("animal_id" == "idPk"))
detections_month <- detections %>% dplyr::mutate(year = lubridate::year(date_time),
                                                 month = lubridate::month(date_time, label = T, abbr = T),
                                                 month_count = lubridate::month(date_time, label = F),
                                                 monthyear = paste0(month, "-", year)) %>%
  dplyr::group_by(animal_id, station_name, monthyear) %>%
  dplyr::summarise(n_detections = n(),
                   year = year[1],
                   month = month[1],
                   month_count = month_count[1],
                   date = as.POSIXct(paste0(year, "-", month_count, "-28"), tz = "UTC"),
                   deploy_latitude = deploy_latitude[1],
                   deploy_longitude = deploy_longitude[1])


# RECEIVER STATIONS
stations <- detections %>% #dplyr::select(station_name, deploy_latitude, deploy_longitude) %>% unique() %>%
  group_by(station_name) %>%
  summarise(deploy_latitude = mean(deploy_latitude),
            deploy_longitude = mean(deploy_longitude))

# deployments <- detections %>% dplyr::select(station_name, deploy_latitude, deploy_longitude, deployment_id, receiver_id) %>% unique()


```



Column {data-width=450 .tabset}
-------------------------------------
    
### Acoustic receivers
    
```{r map}

# EMODnet Bathymetry layer
emodnet_tiles <-"https://tiles.emodnet-bathymetry.eu/2020/baselayer/web_mercator/{z}/{x}/{y}.png"
cite_emodnet <- "<a href='https://emodnet.ec.europa.eu'>EMODnet</a>"
attr(cite_emodnet, "class") <- c("html", "character")

# special icons
# a single icon is declared
icon_tag <- leaflet::makeAwesomeIcon(
  icon = "tag",
  iconColor = "black",
  markerColor = "yellow",
  library = "fa"
)

# colour palettes
col_fun <- scico::scico(n = stations$deploy_latitude %>% unique() %>% length(),
                        palette = "roma")
pal <- leaflet::colorFactor(col_fun, domain = stations$deploy_latitude)
qpal <- colorQuantile(col_fun, domain = stations$deploy_latitude, n = 5)
palette_latitudes_df <- tibble(deploy_latitude = stations$deploy_latitude, color = pal(stations$deploy_latitude))


legend_latitudes <- stations %>% 
  dplyr::mutate(bin_n5 = deploy_latitude %>% dplyr::ntile(n = 5)) %>%
  dplyr::group_by(bin_n5) %>%
  dplyr::summarise(min = deploy_latitude %>% min(),
                   max = deploy_latitude %>% max()) %>%
  dplyr::mutate(color = qpal(stations$deploy_latitude) %>% unique())

leaflet() %>% 
  
#background
  # addTiles() %>%
  addProviderTiles("Esri.WorldImagery", options = providerTileOptions(opacity = 0.6), group = "satellite") %>%
  leaflet::addTiles(urlTemplate = emodnet_tiles,
                    # options = leaflet::tileOptions(tms = FALSE),
                    attribution = cite_emodnet,
                    group = "EMODnet bathymetry") %>%
  # addRasterImage(bathy_belgium_raster, opacity = 1, colors = "Spectral", group = "bathymetry") %>%
  # addPolygons(data = coastline_BE_poly, opacity = 1, fillColor = "grey", weight = 0, fillOpacity = 0.7, group = "bathymetry") %>% #"#ECE4BF"
  addTiles(group = "OpenStreetMap") %>%

#data: receiver stations
  addCircleMarkers(data = stations,
                   # clusterOptions = markerClusterOptions(showCoverageOnHover = F, zoomToBoundsOnClick = T, freezeAtZoom = 7),
                   lat = ~deploy_latitude,
                   lng = ~deploy_longitude,
                   radius = 5,
                   color = "black",
                   weight = 1,
                   fillOpacity = 1,
                   fillColor = ~pal(deploy_latitude),
                   opacity = 1,
                   label = ~paste0("station ", station_name),
                   popup = ~paste0("lat: ", deploy_latitude, ", lon: ", deploy_longitude),
                   group = "receiver stations"
                   ) %>%
  
#data: tagging locations
  addAwesomeMarkers(data = tagging_locations,
                   icon = icon_tag,
                   clusterOptions = markerClusterOptions(), #showCoverageOnHover = T, zoomToBoundsOnClick = T, 
                   lat = ~releaseLatitude,
                   lng = ~releaseLongitude,
                   # radius = 5,
                   # fillOpacity = 0.7,
                   # fillColor = "yellow",
                   # opacity = 0,
                   label = ~paste0("name: ", tagging_location),
                   popup = ~paste0("lat: ", releaseLatitude, ", lon: ", releaseLongitude, ", #sharks tagged: ", ind_tagged),
                   group = "tagging locations"
                   ) %>%

# add-ons
leaflet.extras::addFullscreenControl() %>%
  leafem::addMouseCoordinates() %>%
  addScaleBar(position = "bottomright",
              options = scaleBarOptions(
                maxWidth = 150,
              imperial = FALSE)) %>%
  
# layers control
  addLayersControl(position = "topright" ,
                   baseGroups = c("EMODnet bathymetry", "satellite", "OpenStreetMap"),
                   overlayGroups = c("receiver stations", "tagging locations"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup("tagging locations") %>%
  
# legend
  addLegend(position = "bottomleft",
            colors = legend_latitudes$color %>% rev(),
            labels = paste0(legend_latitudes$min %>% round(), " - ", legend_latitudes$max %>% round()) %>% rev(),
            opacity = 1,
            title = "Latitude")


```
  
<!-- > Map with receiver deployments and acoustic detections. -->

### Questions

### Improvements
 
Column {data-width=650}
-------------------------------------   

    
### Acoustic detections {data-height=600}
    
```{r abacus}

plot_abacus_month <- ggplot() +
  geom_vline(xintercept = animals$catchedDateTime[1] %>% as.POSIXct(tz = "UTC"), 
             colour = "red", linewidth = 2) +
  geom_point(data = detections_month %>% dplyr::mutate(animal_id = animal_id %>% as.character()),
             aes(x = date, y = animal_id, colour = deploy_latitude, size = n_detections)) + 
  labs(x = "date", y = "animal id", size = "# detections", colour = "latitude") +
  scale_x_datetime(date_breaks = "6 months",
                   date_minor_breaks = "1 month",
                   date_labels = "%b '%y"
                   # ,expand = c(0,0)
  ) +
  scico::scale_color_scico(palette = "roma") +
  theme_bw()

plot_abacus_month %>% plotly::ggplotly()

```

> All individuals were tagged in late July, 2016, in Loch Etive (Scotland). The abacus plot shows the detections per month for each individual. The colour denotes the latitude of the detection. 


### {data-height=400}

```{r table}

# make table
table_animals <- DT::datatable(animals %>%
                                 dplyr::select(idPk, tagging_location, utcReleaseDateTime, sex, tag, releaseLatitude, releaseLongitude) %>%
                                 dplyr::rename(animal_id = idPk, release_date_time = utcReleaseDateTime, release_location = tagging_location,
                                               release_latitude = releaseLatitude, release_longitude = releaseLongitude),
              rownames = F,
              filter = 'bottom',
              extension = 'Buttons',options = list(
                dom = 'Bfrtip',
                buttons = c('pdf', 'csv', 'excel', 'print','copy'),
                columnDefs = list(list(className = 'dt-center', targets = '_all'))
              )
            ) %>%
  formatStyle(
  c('animal_id', 'sex'),
  fontWeight = "bold") %>%
  formatStyle(
  'sex',
  backgroundColor = styleEqual(c("F", "M"), c('#FFBB81', '#89B6BD')))

# make plot

# with s. acanthias data
p_f <- ggplot(detections %>%
         dplyr::filter(sex == "F") %>%
         dplyr::mutate(month = lubridate::month(date_time, label = T, abbr = T)), 
       aes(x = deploy_latitude,y = month,  fill = stat(x))) +
  geom_density_ridges_gradient(scale = 2) + #, rel_min_height = 0.01
  # scale_fill_viridis_c(name = "Latitude", option = "C") +
  scico::scale_fill_scico(palette = "roma") +
  labs(y = "month", x = "latitude", fill = "latitude", title = "female") +
  coord_flip() +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw()

# p_f

p_m <- ggplot(detections %>%
         dplyr::filter(sex == "M") %>%
         dplyr::mutate(month = lubridate::month(date_time, label = T, abbr = T)), 
       aes(x = deploy_latitude,y = month,  fill = stat(x))) +
  geom_density_ridges_gradient(scale = 2) + #, rel_min_height = 0.01
  # scale_fill_viridis_c(name = "Latitude", option = "C") +
  scico::scale_fill_scico(palette = "roma") +
  labs(y = "month", x = "latitude", fill = "latitude", title = "male") +
  coord_flip() +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw()

# p_m

ggsave(filename = paste0(getwd(), "/plots/ridgeline_detections_f.png"), plot = p_f)
ggsave(filename = paste0(getwd(), "/plots/ridgeline_detections_m.png"), plot = p_m)

tabsetPanel(
  tabPanel("Info about tagged animals",
           table_animals),
  tabPanel("Latitudinal distribution",
           gridExtra::grid.arrange(p_f, p_m, nrow = 1))
)

```




