---
title: "Squalus acanthias ETN detections overview"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: 
      version: 4
      bootswatch: litera
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo = F}

# knitr::opts_chunk$set(echo = F)
# Sys.setlocale("LC_TIME", "English") # language = English, does not work right now

# fundamentals
# library(devtools)
# devtools::install_github("lifewatch/mregions2")
library(flexdashboard)
library(etn)
library(knitr)
library(shiny)
library(mregions2)

# data wrangling
library(readr)
library(tidyverse)
library(lubridate)
library(dplyr)
library(lubridate)
library(utils)
library(tidyverse)
library(sf)

# maps
library(leaflet)
library(leafem)

# plotting and tables
library(DT) # for interactive tables
library(ggplot2)
library(kableExtra)
library(plotly)
library(scico) #colour palettes
library(gridExtra)
library(ggridges)

# database connection
con <- etn::connect_to_etn(Sys.getenv("userid"), Sys.getenv("pwd"))

```


```{r database query, include=FALSE, echo=FALSE}

shad <- "Alosa fallax"

# get all animals with the species name 
# animals_shad <- etn::get_animals(con, scientific_name = "Alosa fallax")

# animals_shad %>% dplyr::filter(animal_id == 65036)

# ANIMALS
animals_shad <- etn::get_animals(con, scientific_name = shad) %>%
  dplyr::filter(lubridate::year(release_date_time) == 2023)


# TAGGING LOCATIONS
tagging_locations_shad <- animals_shad %>% 
  group_by(release_location) %>%
  summarise(release_latitude = release_latitude[1],
            release_longitude = release_longitude[1],
            ind_tagged = n())
  
# DETECTIONS
detections_shad <- etn::get_acoustic_detections(scientific_name = shad) %>%
  dplyr::filter(lubridate::year(date_time) == 2023) %>%
  dplyr::left_join(animals_shad %>% 
                     dplyr::select(animal_id, release_date_time, sex), 
                   by = "animal_id") %>%
  dplyr::mutate(area = ifelse(acoustic_project_code %in% c("ws1", "ws2", "ws3", "zeeschelde"), acoustic_project_code, "bpns"))

shads_2023 <- detections_shad %>% group_by(animal_id) %>%
  summarise(first_detection = min(date_time)) %>%
  dplyr::filter(first_detection > "2023-04-25" %>% as.POSIXct(tz = "utc")) %>%
  mutate(tagged_2023 = TRUE)

detections_shad <- detections_shad %>%
  # mutate(tagged_2023 = FALSE) %>%
  left_join(shads_2023, by = "animal_id") %>%
  filter(tagged_2023 = TRUE)

detections_month_shad <- detections_shad %>% 
  dplyr::mutate(year = lubridate::year(date_time),
                month = lubridate::month(date_time, label = T, abbr = T),
                month_count = lubridate::month(date_time, label = F),
                monthyear = paste0(month, "-", year)) %>%
  dplyr::group_by(animal_id, station_name, monthyear) %>%
  dplyr::summarise(n_detections = n(),
                   year = year[1],
                   month = month[1],
                   month_count = month_count[1],
                   date = as.POSIXct(paste0(year, "-", month_count, "-28"), tz = "UTC"),
                   deploy_latitude = deploy_latitude[1],
                   deploy_longitude = deploy_longitude[1])


# RECEIVER STATIONS
stations_shad <- detections_shad %>% 
  group_by(station_name) %>%
  summarise(deploy_latitude = mean(deploy_latitude),
            deploy_longitude = mean(deploy_longitude),
            n_detections = n(),
            n_individuals = animal_id %>% unique() %>% length())

# DEPLOYMENTS
# all_acoustic_project_codes <- etn::list_acoustic_project_codes() %>% as_tibble()
# is there any better way to get all deployments in an area?

# detections_shad$acoustic_project_code %>% unique()

acoustic_projects_codes <- c('bovenschelde', 'bpns', 'FISHINTEL', 'lifewatch', 'PelFish', 'rt2020_zeeschelde', 'thornton', 'ws1', 'ws2', 'ws3', 'zeeschelde', 'cpodnetwork') 

deployments_bpns_ws <- etn::get_acoustic_deployments(acoustic_project_code = acoustic_projects_codes) %>%
  dplyr::filter(lubridate::year(deploy_date_time) == 2023 | lubridate::year(recover_date_time) == 2023)

# dep_schelde <- deployments_bpns_ws %>% dplyr::filter(deploy_longitude > 3.9) %>% View() # these are the weird deployments where no shads were detected

receiver_stations <- deployments_bpns_ws %>% 
  dplyr::group_by(station_name, acoustic_project_code) %>%
  dplyr::summarise(deploy_latitude = mean(deploy_latitude),
                  deploy_longitude = mean(deploy_longitude)) %>%
  tidyr::drop_na() %>%
  dplyr::filter(deploy_longitude > 1) %>%
  dplyr::mutate(area = ifelse(acoustic_project_code %in% c("ws1", "ws2", "ws3", "zeeschelde"), acoustic_project_code, "bpns"))

# TAGS
tags_shad <- etn::get_tags(acoustic_tag_id = detections_shad$acoustic_tag_id %>% unique())
```


```{r other queries, include=FALSE, echo=FALSE}
# EEZs
Dutch_EEZ <-  mregions2::gaz_search(5668) %>% mregions2::gaz_geometry()
BPNS <- mregions2::gaz_search(3293) %>% mregions2::gaz_geometry()
French_EEZ <- mregions2::gaz_search(5677) %>% mregions2::gaz_geometry()
UK_EEZ <- mregions2::gaz_search(5696) %>% mregions2::gaz_geometry()

EEZs <- rbind(Dutch_EEZ, BPNS, French_EEZ, UK_EEZ)

# coastline to separate BPNS into offshore and onshore

# coastline_file <- utils::download.file("https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_coastline.zip", 
#                                 destfile = paste0(getwd(), "/data/ne_10m_coastline.zip"), mode = "wb")

# TODO: find out how to unzip files
# coastline <- sf::st_read(paste0(getwd(), "/data/ne_10m_coastline.shp"))

# receiver_stations <- receiver_stations %>%
#   dplyr::mutate(st_as_sf(., coords = c("deploy_longitude", "deploy_latitude"), crs = st_crs(coastline)) %>% dplyr::select(geometry))
```



Column {data-width=450 .tabset}
-------------------------------------
    
### Acoustic receivers
    
```{r map}

# EMODnet Bathymetry layer
emodnet_tiles <-"https://tiles.emodnet-bathymetry.eu/2020/baselayer/web_mercator/{z}/{x}/{y}.png"
cite_emodnet <- "<a href='https://emodnet.ec.europa.eu'>EMODnet</a>"
attr(cite_emodnet, "class") <- c("html", "character")

# special icons
# a single icon is declared
icon_tag <- leaflet::makeAwesomeIcon(
  icon = "tag",
  iconColor = "black",
  markerColor = "yellow",
  library = "fa"
)

# colour palette
col_fun <- scico::scico(n = receiver_stations$area %>% unique() %>% length(),
                        palette = "managua")
pal <- leaflet::colorFactor(col_fun, domain = receiver_stations$area)
# qpal <- colorQuantile(col_fun, domain = stations_shad$deploy_latitude, n = 5)
# palette_latitudes_df <- tibble(deploy_latitude = stations_shad$deploy_latitude, color = pal(stations_shad$deploy_latitude))

legend_stations <- tibble(area = receiver_stations$area %>% unique(),
                          colour = pal(area))
# 
# legend_latitudes <- stations_shad %>%
#   dplyr::mutate(bin_n5 = deploy_latitude %>% dplyr::ntile(n = 5)) %>%
#   dplyr::group_by(bin_n5) %>%
#   dplyr::summarise(min = deploy_latitude %>% min(),
#                    max = deploy_latitude %>% max()) %>%
#   dplyr::mutate(color = qpal(stations_shad$deploy_latitude) %>% unique())

leaflet() %>% 
  setView(3.3, 51.296, zoom = 8) %>% 
#background
  # addTiles() %>%
  addProviderTiles("Esri.WorldImagery", options = providerTileOptions(opacity = 0.6), group = "satellite") %>%
  leaflet::addTiles(urlTemplate = emodnet_tiles,
                    # options = leaflet::tileOptions(tms = FALSE),
                    attribution = cite_emodnet,
                    group = "EMODnet bathymetry") %>%
  # addRasterImage(bathy_belgium_raster, opacity = 1, colors = "Spectral", group = "bathymetry") %>%
  # addPolygons(data = coastline_BE_poly, opacity = 1, fillColor = "grey", weight = 0, fillOpacity = 0.7, group = "bathymetry") %>% #"#ECE4BF"
  addTiles(group = "OpenStreetMap") %>%
  
# EEZs
  addPolygons(data = EEZs, color = "darkgrey", 
              weight = 2,
              opacity = 1.0,
              popup = ~preferredGazetteerName,
              fillOpacity = 0, 
              group = "EEZs") %>%
  
#### area rectangles ####
  addRectangles( #WS1
  lng1 = 3.387, lat1 = 51.365, lng2 = 3.666, lat2 = 51.513,
  fillOpacity = 0.2, weight = 2, color = legend_stations$colour[legend_stations$area == "ws1"], group = "receiver areas") %>%
  addRectangles( #WS2
  lng1 = 3.68, lat1 = 51.314, lng2 = 3.859, lat2 = 51.447,
  fillOpacity = 0.2, weight = 2, color = legend_stations$colour[legend_stations$area == "ws2"], group = "receiver areas") %>%
  addRectangles( #WS3
  lng1 = 3.99, lat1 = 51.377, lng2 = 4.06, lat2 = 51.450,
  fillOpacity = 0.2, weight = 2, color = legend_stations$colour[legend_stations$area == "ws3"], group = "receiver areas") %>%
  addRectangles( #zeeschelde
  lng1 = 3.889, lat1 = 50.965, lng2 = 4.510, lat2 = 51.325,
  fillOpacity = 0.2, weight = 2, color = legend_stations$colour[legend_stations$area == "zeeschelde"], group = "receiver areas") %>%
  addPolygons(data = BPNS, color = legend_stations$colour[legend_stations$area == "bpns"],weight = 2, fillOpacity = 0.15, group = "receiver areas") %>%

# data: deployments
    addCircleMarkers(data = receiver_stations,
                   # clusterOptions = markerClusterOptions(showCoverageOnHover = F, zoomToBoundsOnClick = T, freezeAtZoom = 7),
                   lat = ~deploy_latitude,
                   lng = ~deploy_longitude,
                   radius = 4,
                   color = "black",
                   weight = 1,
                   fillOpacity = 1,
                   fillColor = "black", #~pal(area)
                   opacity = 1,
                   label = ~paste0("station ", station_name, ", project: ", acoustic_project_code),
                   popup = ~paste0("lat: ", deploy_latitude, ", lon: ", deploy_longitude),
                   group = "receiver stations"
                   ) %>%
  
#data: receiver stations with detections
  addCircleMarkers(data = stations_shad,
                   # clusterOptions = markerClusterOptions(showCoverageOnHover = F, zoomToBoundsOnClick = T, freezeAtZoom = 7),
                   lat = ~deploy_latitude,
                   lng = ~deploy_longitude,
                   radius = ~log(n_detections) * 1.5,
                   color = "black",
                   weight = 0.5,
                   fillOpacity = 1,
                   fillColor = "orange", #~pal(deploy_latitude),
                   opacity = 1,
                   label = ~paste0("station ", station_name, ", # detections: ", n_detections, ", # individuals: ", n_individuals),
                   popup = ~paste0("lat: ", deploy_latitude, ", lon: ", deploy_longitude),
                   group = "<span style=color:orange># detections</span>"
                   ) %>%
  
  #data: receiver stations with # indiviuals
  addCircleMarkers(data = stations_shad,
                   # clusterOptions = markerClusterOptions(showCoverageOnHover = F, zoomToBoundsOnClick = T, freezeAtZoom = 7),
                   lat = ~deploy_latitude,
                   lng = ~deploy_longitude,
                   radius = ~log(n_individuals) * 2,
                   color = "black",
                   weight = 0.5,
                   fillOpacity = 1,
                   fillColor = "purple", #~pal(deploy_latitude),
                   opacity = 1,
                   label = ~paste0("station ", station_name, ", # detections: ", n_detections, ", # individuals: ", n_individuals),
                   popup = ~paste0("lat: ", deploy_latitude, ", lon: ", deploy_longitude),
                   group = "<span style=color:purple># individuals</span>"
                   ) %>%
  
#data: tagging locations
  addAwesomeMarkers(data = tagging_locations_shad,
                   icon = icon_tag,
                   lat = ~release_latitude,
                   lng = ~release_longitude,
                   label = ~paste0("name: ", release_location),
                   popup = ~paste0("lat: ", release_latitude, ", lon: ", release_longitude, ", #fish tagged: ", ind_tagged),
                   group = "tagging locations"
                   ) %>%

# add-ons
leaflet.extras::addFullscreenControl() %>%
  leafem::addMouseCoordinates() %>%
  addScaleBar(position = "bottomright",
              options = scaleBarOptions(
                maxWidth = 150,
              imperial = FALSE)) %>%
  
# layers control
  addLayersControl(position = "topright" ,
                   baseGroups = c("OpenStreetMap", "EMODnet bathymetry", "satellite"),
                   overlayGroups = c("<span style=color:orange># detections</span>", "<span style=color:purple># individuals</span>","tagging locations", "receiver areas"), # "receiver stations",
                   options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup(c("tagging locations", "<span style=color:orange># detections</span>")) %>%
  
# legend
  addLegend(position = "bottomleft",
            labels = legend_stations$area,
            colors = legend_stations$colour,
            opacity = 1,
            title = "Receiver area")

```
  
> Map with receiver deployments and acoustic detections. The radius of the circles correspond to either the amount of acoustic detections or the amount of individual fish detected at a receiver station.


 
Column {data-width=650}
-------------------------------------   

    
### Acoustic detections {data-height=600}
    
```{r abacus}

plot_abacus <- ggplot(data = detections_shad %>% 
                        dplyr::filter(tagged_2023 = TRUE) %>%
               dplyr::mutate(animal_id = animal_id %>% 
                               as.character(),
                             area = area %>% as.factor())) +
  geom_point(aes(x = date_time, y = animal_id, colour = area)) + 
  labs(x = "date", y = "animal id", colour = "area") +
  scale_x_datetime(date_breaks = "1 month",
                   # date_minor_breaks = "2 weeks",
                   date_labels = "%b '%y"
                   # ,expand = c(0,0)
  ) +
  # scico::scale_color_scico(palette = "roma") +
  scale_color_manual(values = legend_stations %>% dplyr::filter(area %in% (detections_shad$area %>% unique())) %>% dplyr::select(colour) %>% pull()) + 
  theme_bw()

plot_abacus %>% plotly::ggplotly()

```


### {data-height=400}

```{r table}

detections_shad_area <- detections_shad %>% group_by(area) %>% 
  dplyr::summarise(n_detections = n(),
                   n_individuals = animal_id %>% unique() %>% length())

DT::datatable(detections_shad_area,
              rownames = F,
              # filter = 'bottom',
              extension = 'Buttons',options = list(
                dom = 'Bfrtip',
                buttons = c('pdf', 'csv', 'excel', 'print','copy'),
                columnDefs = list(list(className = 'dt-center', targets = '_all'))
              )
            )

# # make table
# table_animals <- DT::datatable(animals %>%
#                                  dplyr::select(idPk, tagging_location, utcReleaseDateTime, sex, tag, releaseLatitude, releaseLongitude) %>%
#                                  dplyr::rename(animal_id = idPk, release_date_time = utcReleaseDateTime, release_location = tagging_location,
#                                                release_latitude = releaseLatitude, release_longitude = releaseLongitude),
#               rownames = F,
#               filter = 'bottom',
#               extension = 'Buttons',options = list(
#                 dom = 'Bfrtip',
#                 buttons = c('pdf', 'csv', 'excel', 'print','copy'),
#                 columnDefs = list(list(className = 'dt-center', targets = '_all'))
#               )
#             ) %>%
#   formatStyle(
#   c('animal_id', 'sex'),
#   fontWeight = "bold") %>%
#   formatStyle(
#   'sex',
#   backgroundColor = styleEqual(c("F", "M"), c('#FFBB81', '#89B6BD')))


```




