---
title: "ETN receiver management"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    horizontal_layout: fill
    theme: 
      version: 4
      bootswatch: litera
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE, echo = F}

# knitr::opts_chunk$set(echo = F)
# Sys.setlocale("LC_TIME", "English") # language = English, does not work right now

# fundamentals
library(flexdashboard)
library(etn)
library(knitr)

# data wrangling
library(readr)
# library(tidyverse)
library(lubridate)
library(dplyr)
library(lubridate)
library(utils)

# maps
library(leaflet)
library(leafem)

# plotting and tables
library(DT) # for interactive tables
library(ggplot2)
library(kableExtra)
library(plotly)
library(scico) #colour palettes

# database connection
con <- etn::connect_to_etn(Sys.getenv("userid"), Sys.getenv("pwd"))


```



```{r database query, include=FALSE}

# get currently active deployments IN THE 'ws1' and 'ws2' projects
current_deployments <- etn::get_acoustic_deployments(con,
                                                  acoustic_project_code = c("ws1", "ws2"),
                                                  open_only = T) # todo: change to both open and closed

# make new column to indicate if battery needs change or not
current_deployments <- current_deployments %>%
  dplyr::mutate(needs_battery_change = NA,
                colour = "black")

today <- "2023-09-25" %>% as.POSIXct(tz = "CET")
cutoff_date <- today + months(3)
# class(today + months(3)) # check class of cutoff date

# assess if battery needs change
current_deployments <- current_deployments %>%
  dplyr::mutate(needs_battery_change = ifelse(battery_estimated_end_date < cutoff_date,
                                              1,
                                              0),
                colour = ifelse(needs_battery_change == 1, "#F9938E", "#90BF87")) %>%
  dplyr::arrange(desc(needs_battery_change))
```



Row
-------------------------------------
    
### Receiver position and status
    
```{r map}

# EMODnet Bathymetry layer
emodnet_tiles <-"https://tiles.emodnet-bathymetry.eu/2020/baselayer/web_mercator/{z}/{x}/{y}.png"
cite_emodnet <- "<a href='https://emodnet.ec.europa.eu'>EMODnet</a>"
attr(cite_emodnet, "class") <- c("html", "character")


receiver_map <- leaflet(leafletOptions(minZoom = 11)) %>% 
  #background
  addTiles(group = "OpenStreetMap") %>%
  addProviderTiles("Esri.WorldImagery", options = providerTileOptions(opacity = 0.6), group = "satellite") %>%
  leaflet::addTiles(urlTemplate = emodnet_tiles,
                    # options = leaflet::tileOptions(tms = FALSE),
                    attribution = cite_emodnet,
                    group = "EMODnet bathymetry") %>%
  # addRasterImage(bathy_belgium_raster, opacity = 1, colors = "Spectral", group = "bathymetry") %>%
  # addPolygons(data = coastline_BE_poly, opacity = 1, fillColor = "grey", weight = 0, fillOpacity = 0.7, group = "bathymetry") %>% #"#ECE4BF"
  
  # NEED BATTERY CHANGE
  addCircleMarkers(data = current_deployments %>% dplyr::filter(needs_battery_change == 1),
                   lat = ~deploy_latitude,
                   lng = ~deploy_longitude,
                   radius = 5,
                   opacity = 0,
                   fillOpacity = 0.7,
                   fillColor = "red",
                   popup = ~paste0("station: ", station_name, 
                                   ", id: ", receiver_id,
                                   ", lat: ", deploy_latitude %>% round(digits = 2), ", lng: ", deploy_longitude  %>% round(digits = 2)),
                   label = ~paste0("battery start: ", battery_installation_date %>% format("%Y-%m-%d"),
                                   ", battery end: ", battery_estimated_end_date %>% format("%Y-%m-%d"))
  ) %>%
  
  # DON'T NEED BATTERY CHANGE
  addCircleMarkers(data = current_deployments %>% dplyr::filter(needs_battery_change == 0),
                   lat = ~deploy_latitude,
                   lng = ~deploy_longitude,
                   radius = 5,
                   opacity = 0,
                   fillOpacity = 0.7,
                   fillColor = "green",
                   popup = ~paste0("station: ", station_name, 
                                   ", id: ", receiver_id,
                                   ", lat: ", deploy_latitude %>% round(digits = 2), ", lng: ", deploy_longitude  %>% round(digits = 2)),
                   label = ~paste0("battery start: ", battery_installation_date %>% format("%Y-%m-%d"),
                                   ", battery end: ", battery_estimated_end_date %>% format("%Y-%m-%d"))
  ) %>%
  
  # MISSING INFORMATION
  addCircleMarkers(data = current_deployments %>% dplyr::filter(is.na(needs_battery_change)),
                   lat = ~deploy_latitude,
                   lng = ~deploy_longitude,
                   radius = 5,
                   opacity = 0,
                   fillOpacity = 0.7,
                   fillColor = "black",
                   popup = ~paste0("station: ", station_name, 
                                   ", id: ", receiver_id,
                                   ", lat: ", deploy_latitude %>% round(digits = 2), ", lng: ", deploy_longitude  %>% round(digits = 2)),
                   label = ~paste0("battery start: ", battery_installation_date %>% format("%Y-%m-%d"),
                                   ", battery end: ", battery_estimated_end_date %>% format("%Y-%m-%d"))
  ) %>%
  
  # LEGEND
  addLegend(position = "bottomleft", opacity = 1,
            colors = c("red", "green", "black"), labels = c("battery needs change", "battery is OK", "missing information")) %>%

  
  # add-ons
leaflet.extras::addFullscreenControl() %>%
  leafem::addMouseCoordinates() %>%
  addScaleBar(position = "bottomright",
              options = scaleBarOptions(
                maxWidth = 150,
              imperial = FALSE)) %>%

  
  # layers control
  addLayersControl(position = "topright" ,
                   baseGroups = c("OpenStreetMap", "EMODnet bathymetry", "satellite"),
                   # overlayGroups = c("receiver stations", "tagging locations"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
  hideGroup("tagging locations")


receiver_map
  
```

> When you hover over the map, the fields `battery_installation_date` and `battery_estimated_end_date` are displayed. 
  By clicking on a receiver, the fields `station_name`, `receiver_id`, `deploy_latitude` and `deploy_longitude` are displayed.

<!-- > Map with receiver deployments. Colours indicate the time left to the estimated battery end date of the receiver. -->


Row
-------------------------------------    
    
### Receiver deployment info

```{r table}

DT::datatable(current_deployments %>%
              dplyr::mutate(deploy_date_time = deploy_date_time %>% format("%Y-%m-%d"),
                            battery_installation_date = battery_installation_date %>% format("%Y-%m-%d"),
                            battery_estimated_end_date = battery_estimated_end_date %>% format("%Y-%m-%d")) %>%
               dplyr::select(receiver_id, needs_battery_change, station_name, deploy_latitude, deploy_longitude, 
                             battery_installation_date, battery_estimated_end_date,  deploy_date_time, acoustic_project_code),
              rownames = F,
              filter = 'top',
              extension = 'Buttons',
              options = list(
                pageLength = 50, # autoWidth = TRUE,
                dom = 'Bfrtip',
                buttons = c('pdf', 'csv', 'excel', 'print','copy'),
                columnDefs = list(list(className = 'dt-center', targets = '_all')))
              ) %>%
  formatStyle(
  c('receiver_id', 'battery_estimated_end_date'),
  fontWeight = "bold") %>%
  formatStyle(
  'needs_battery_change',
  backgroundColor = styleEqual(c(0, 1), c('#90BF87', '#F9938E')))

# table_animals <- 
#   DT::datatable(animals %>% 
#                   dplyr::select(idPk, utcReleaseDateTime, sex, tag, releaseLatitude, releaseLongitude) %>%
#                   dplyr::rename(animal_id = idPk, release_date_time = utcReleaseDateTime,  release_latitude = releaseLatitude, release_longitude = releaseLongitude), #release_location = tagging_location,
#               rownames = F,
#               filter = 'bottom',
#               extension = 'Buttons',options = list(
#                 dom = 'Bfrtip',
#                 buttons = c('pdf', 'csv', 'excel', 'print','copy'),
#                 columnDefs = list(list(className = 'dt-center', targets = '_all'))
#               )
#             ) %>%
#   formatStyle(
#   c('animal_id', 'sex'),
#   fontWeight = "bold") %>%
#   formatStyle(
#   'sex',
#   backgroundColor = styleEqual(c("F", "M"), c('#FFBB81', '#89B6BD')))

```




