---

title: "Bike Shares Daily"

output: 

  flexdashboard::flex_dashboard:

    orientation: columns

    vertical_layout: fill

---



```{r setup, include=FALSE}

library(flexdashboard)

library(readr)

library(tidyverse)

library(lubridate)

library(plotly)



trips_df <- read_csv('https://assets.datacamp.com/production/course_6355/datasets/sanfran_bikeshare_joined_oneday.csv')

```



Overview

====================================================



Column {data-width=650}

-----------------------------------------------------------------------



### Origins





Column {data-width=350}

-----------------------------------------------------------------------



### Median Trip Length



```{r}



median_min <- median(trips_df$duration_sec / 60) %>% round(digits = 1)



valueBox(median_min, 

         caption = 'Median Trip Duration (Minutes)', 

         icon = 'fa-clock-o',

         href = '#trip-duration'

)





```



### % Short Trips





### Trips by Start Time





Trip Duration

====================================================



### Trip Durations



```{r}



duration_plot <- trips_df %>%

  mutate(`Trip Duration (min)` = duration_sec / 60) %>%

  ggplot(aes(x = `Trip Duration (min)`)) +

  theme_bw() +

  geom_histogram(binwidth = 1) +

  ylab('# Trips')



duration_plot %>% ggplotly()



```